#!/usr/bin/env python3
"""Convert the reference-conditioned CNN to an int8 TFLite model for ESP32-S3.

Pipeline: detect/pill_classifier.onnx  ->  TensorFlow  ->  int8 TFLite  ->
src/model_data.h (a C byte array TFLite Micro loads on the device).

Why int8: the ESP32-S3 has no FPU-heavy NN path but does have SIMD int8 MACs;
full-integer quantization is what makes the 80k-param CNN run in real time and
shrinks it to ~80 KB. Quantization needs a *representative dataset* — real
6-channel inputs (cell RGB + empty-reference RGB) so the converter can pick
per-tensor scales; we build it from an export produced by
detect/export_dataset.py plus the shipped reference cells.

This runs OFF the device, in a desktop/CI environment with tensorflow +
onnx2tf installed (NOT on the Pi and NOT on the ESP32):

    pip install tensorflow onnx2tf onnx onnx-graphsurgeon numpy opencv-python-headless
    python3 firmware/esp32s3_cnn_inference/convert_cnn_to_tflite.py \
        --onnx detect/pill_classifier.onnx \
        --cells <export_or_cells_dir> \
        --reference detect/reference_cells \
        --out firmware/esp32s3_cnn_inference/src/model_data.h

The generated header is git-ignored; regenerate it whenever the CNN is
retrained. See README.md for the accuracy-vs-int8 check to run afterwards.
"""
import argparse
import subprocess
import sys
from pathlib import Path

import numpy as np

IN_C, IN_H, IN_W = 6, 128, 96  # matches detect/train_classifier.py


def build_representative(cells_dir, reference_dir, limit=200):
    """Yield up to `limit` real 6-channel inputs (NHWC, float32 [0,1]).

    Mirrors detect/pipeline.py's input construction: cell RGB in channels 0-2,
    the matching empty-reference cell RGB in channels 3-5, resized to 128x96.
    TFLite wants NHWC, so channels go last.
    """
    import cv2

    refs = {}
    for p in Path(reference_dir).glob("*.jpg"):
        img = cv2.resize(cv2.imread(str(p)), (IN_W, IN_H), interpolation=cv2.INTER_AREA)
        refs[p.stem] = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    if not refs:
        sys.exit(f"no reference crops in {reference_dir}")

    samples = []
    # Accept either an export tree (Train/Full/<stem>_<DAY>_<SLOT>.jpg) or a
    # crop_cells tree (<stem>/<DAY>_<SLOT>.jpg). Match each crop to its ref cell.
    for jpg in sorted(Path(cells_dir).rglob("*.jpg")):
        cell_key = None
        for stem in refs:  # filename ends with the DAY_SLOT that names the ref
            if jpg.stem.endswith(stem):
                cell_key = stem
                break
        if cell_key is None:
            continue
        img = cv2.imread(str(jpg))
        if img is None:
            continue
        img = cv2.cvtColor(cv2.resize(img, (IN_W, IN_H), interpolation=cv2.INTER_AREA),
                           cv2.COLOR_BGR2RGB)
        six = np.concatenate([img, refs[cell_key]], axis=2).astype(np.float32) / 255.0
        samples.append(six)
        if len(samples) >= limit:
            break
    if not samples:
        sys.exit("no representative samples matched a reference cell — check "
                 "--cells (needs crops whose names end in <DAY>_<SLOT>)")
    print(f"representative dataset: {len(samples)} samples")
    return np.stack(samples)  # NHWC


def onnx_to_saved_model(onnx_path, work_dir):
    """NCHW ONNX -> TF SavedModel via onnx2tf (handles the layout transpose)."""
    try:
        import onnx2tf
    except ImportError:
        sys.exit("onnx2tf is required: pip install onnx2tf onnx onnx-graphsurgeon")
    onnx2tf.convert(input_onnx_file_path=str(onnx_path),
                    output_folder_path=str(work_dir),
                    copy_onnx_input_output_names_to_tflite=True,
                    non_verbose=True)
    return work_dir


def to_int8_tflite(saved_model_dir, rep_nhwc):
    import tensorflow as tf

    conv = tf.lite.TFLiteConverter.from_saved_model(str(saved_model_dir))
    conv.optimizations = [tf.lite.Optimize.DEFAULT]

    def rep_gen():
        for s in rep_nhwc:
            yield [s[np.newaxis, ...].astype(np.float32)]

    conv.representative_dataset = rep_gen
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    return conv.convert()


def emit_c_header(tflite_bytes, out_path, var="g_pill_cnn_model"):
    lines = [
        "// AUTO-GENERATED by convert_cnn_to_tflite.py — do not edit.",
        "// int8 TFLite model for the reference-conditioned pill CNN.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        f"alignas(16) const unsigned char {var}[] = {{",
    ]
    for i in range(0, len(tflite_bytes), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in tflite_bytes[i:i + 12])
        lines.append(f"  {chunk},")
    lines.append("};")
    lines.append(f"const size_t {var}_len = {len(tflite_bytes)};")
    Path(out_path).write_text("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--onnx", default="detect/pill_classifier.onnx")
    ap.add_argument("--cells", required=True,
                    help="export/ or dataset/cells dir for the representative set")
    ap.add_argument("--reference", default="detect/reference_cells")
    ap.add_argument("--out", default="firmware/esp32s3_cnn_inference/src/model_data.h")
    ap.add_argument("--workdir", default="/tmp/pill_cnn_tf")
    ap.add_argument("--max-samples", type=int, default=200)
    args = ap.parse_args()

    rep = build_representative(args.cells, args.reference, args.max_samples)
    work = Path(args.workdir)
    work.mkdir(parents=True, exist_ok=True)
    saved = onnx_to_saved_model(args.onnx, work)
    tfl = to_int8_tflite(saved, rep)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    emit_c_header(tfl, args.out)
    print(f"wrote {args.out}  ({len(tfl)/1024:.1f} KB int8 model)")
    print("next: build the firmware (platformio run) and flash; see README.md "
          "for the on-device sanity check.")


if __name__ == "__main__":
    main()
